-- Edinburgh Plain Services - unified database schema
-- Collects every category CSV (nhs, warm, food, period, ...) into one place.
--
-- Source CSV schema (from nhs.ipynb):
--   id,n,c,a,postcode,lat,lng,days,open,close,dt,acc,t,g,org,source,
--   student_only,registration,institution,tags
--
-- Design notes:
--  * One wide `services` table mirrors the CSV columns so any category CSV drops
--    in unchanged. Column `c` (category) is hoisted to `category` and indexed.
--  * `source_file` / `loaded_at` record which CSV a row came from and when, so we
--    can ingest many files over time and trace provenance.
--  * `days` is stored as the raw CSV string (e.g. "0,1,2,3,4,5,6"); parse into
--    service_hours if you need to query per-day openings.
--  * `g` is kept verbatim from the CSV (meaning not yet defined in the source).

PRAGMA journal_mode = WAL;

CREATE TABLE IF NOT EXISTS services (
    id            TEXT PRIMARY KEY,        -- unique within a source; e.g. "n1", "gp_P96001"
    name          TEXT NOT NULL,           -- n
    category      TEXT NOT NULL,           -- c: nhs / warm / food / period / ...
    area          TEXT,                    -- a: locality / address area
    postcode      TEXT,
    lat           REAL,
    lng           REAL,
    days          TEXT,                    -- e.g. "0,1,2,3,4,5,6"
    open_time     TEXT,                    -- open: "00:00"
    close_time    TEXT,                    -- close: "23:59"
    timing_note   TEXT,                    -- dt: "Open 24 hours" / "Daily 08:00-00:00"
    access        TEXT,                    -- acc: "Emergency only" / "Walk-in"
    type          TEXT,                    -- t: what it treats / who it is for
    g             INTEGER,                 -- g: verbatim flag from source (meaning TBD)
    org           TEXT,                    -- org: owning organisation
    source        TEXT,                    -- source: data source / owner
    student_only  INTEGER DEFAULT 0,       -- 0/1
    registration  INTEGER DEFAULT 0,       -- 0/1: does the user need to register?
    institution   TEXT,                    -- institution: "all" or a specific body
    tags          TEXT,                    -- tags: semicolon-separated, e.g. "nhs;emergency"

    -- app-facing fields (optional; may be absent from a raw CSV and filled later,
    -- e.g. description_plain generated by the local model)
    description_original TEXT,
    description_plain    TEXT,
    phone        TEXT,
    website      TEXT,
    free         INTEGER DEFAULT 1,        -- 0/1

    -- provenance (added by the loader, not from the CSV)
    source_file   TEXT,
    loaded_at     TEXT DEFAULT (datetime('now'))
);

-- Lookups we actually do: by category, by postcode/area, by tag.
CREATE INDEX IF NOT EXISTS idx_services_category  ON services(category);
CREATE INDEX IF NOT EXISTS idx_services_postcode  ON services(postcode);
CREATE INDEX IF NOT EXISTS idx_services_area      ON services(area);
CREATE INDEX IF NOT EXISTS idx_services_source    ON services(source_file);
